export const RUSH_QUOTES: { text: string; source: string }[] = [
  // Neil Peart
  { text: "If you choose not to decide, you still have made a choice.", source: "Freewill — Permanent Waves (1980)" },
  { text: "Living in the limelight, the universal dream for those who wish to seem.", source: "Limelight — Moving Pictures (1981)" },
  { text: "Conform or be cast out.", source: "Subdivisions — Signals (1982)" },
  { text: "The spaces in between leave room for you and I to grow.", source: "Entre Nous — Permanent Waves (1980)" },
  { text: "What you own is your own kingdom, what you do is your own glory, what you love is your own power, what you live is your own story.", source: "Something for Nothing — 2112 (1976)" },
  { text: "All this machinery making modern music can still be open-hearted.", source: "The Spirit of Radio — Permanent Waves (1980)" },
  { text: "A spirit with a vision is a dream with a mission.", source: "Mission — Hold Your Fire (1987)" },
  { text: "He knows changes aren't permanent, but change is.", source: "Tom Sawyer — Moving Pictures (1981)" },
  { text: "The point of the journey is not to arrive.", source: "Prime Mover — Presto (1989)" },
  { text: "Quick to judge, quick to anger, slow to understand. Ignorance and prejudice and fear walk hand in hand.", source: "Witch Hunt — Moving Pictures (1981)" },
  { text: "Plus ça change, plus c'est la même chose. The more things change, the more they stay the same.", source: "Circumstances — Hemispheres (1978)" },
  { text: "I will choose a path that's clear. I will choose free will.", source: "Freewill — Permanent Waves (1980)" },
  { text: "One likes to believe in the freedom of music.", source: "The Spirit of Radio — Permanent Waves (1980)" },
  { text: "Glittering prizes and endless compromises shatter the illusion of integrity.", source: "The Spirit of Radio — Permanent Waves (1980)" },
  { text: "You can choose a ready guide in some celestial voice. If you choose not to decide, you still have made a choice.", source: "Freewill — Permanent Waves (1980)" },
  { text: "There is unrest in the forest. There is trouble with the trees.", source: "The Trees — Hemispheres (1978)" },
  { text: "Cast in this unlikely role, ill-equipped to act, with insufficient tact.", source: "Limelight — Moving Pictures (1981)" },
  { text: "Skating away on the thin ice of a new day.", source: "Marathon — Power Windows (1985)" },
  { text: "Hold your fire — keep it burning bright.", source: "Hold Your Fire — Hold Your Fire (1987)" },
  { text: "In the high school halls, in the shopping malls, conform or be cast out.", source: "Subdivisions — Signals (1982)" },
  { text: "We are young, wandering the face of the earth, wondering what our dreams might be worth.", source: "Finding My Way — Rush (1974)" },
  { text: "Some are born to move the world, to live their fantasies. But most of us just dream about the things we'd like to be.", source: "Losing It — Signals (1982)" },
  { text: "Sadder still to watch it die than never to have known it.", source: "Losing It — Signals (1982)" },
  { text: "A modern-day warrior, mean, mean stride. Today's Tom Sawyer, mean, mean pride.", source: "Tom Sawyer — Moving Pictures (1981)" },
  { text: "We can go from boom to bust, from dreams to a bowl of dust.", source: "The Garden — Clockwork Angels (2012)" },
  { text: "The measure of a life is a measure of love and respect, so hard to earn so easily burned.", source: "The Garden — Clockwork Angels (2012)" },
  { text: "I can learn to resist anything but temptation.", source: "Resist — Test for Echo (1996)" },
  { text: "Catch the mist, catch the myth, catch the mystery, catch the drift.", source: "Vital Signs — Moving Pictures (1981)" },

  // Neil Peart (spoken/written)
  { text: "It's not about how many breaths you take, but about the moments that take your breath away.", source: "Neil Peart" },
  { text: "From the point of ignition to the final drive, the point of the journey is not to arrive.", source: "Neil Peart — Prime Mover" },

  // Geddy Lee
  { text: "We always tried to make the kind of music we would want to hear.", source: "Geddy Lee" },
  { text: "We were three guys who were pretty misunderstood in high school... we found each other and we found music.", source: "Geddy Lee" },
  { text: "We wanted to be a better band, a more interesting band. We never wanted to repeat ourselves.", source: "Geddy Lee" },
  { text: "You have to believe that what you're doing is the right thing and not care what other people think.", source: "Geddy Lee — My Effin' Life" },
  { text: "Rush was a democracy of three strong-willed people, and that's what made it work.", source: "Geddy Lee" },
  { text: "Making music with your best friends — that's the dream, isn't it?", source: "Geddy Lee" },

  // Alex Lifeson
  { text: "Blah blah blah, blah blah blah blah, blah blah blah.", source: "Alex Lifeson — Juno Awards (2013)" },
  { text: "Guitar is the best form of self-expression I know. Everything else, and I'm just a ordinary, average guy.", source: "Alex Lifeson" },
  { text: "We were never cool enough to be cool, so we just played as well as we could.", source: "Alex Lifeson" },
  { text: "We didn't set out to change music. We just wanted to make the music we loved.", source: "Alex Lifeson" },
  { text: "Every show was a chance to be better than the last one. We never phoned it in.", source: "Alex Lifeson" },
  { text: "Rush was always about the three of us pushing each other to be better.", source: "Alex Lifeson" },

  // Song lyrics — deeper cuts
  { text: "Attention all planets of the Solar Federation: We have assumed control.", source: "2112 — 2112 (1976)" },
  { text: "Though his mind is not for rent, don't put him down as arrogant.", source: "Tom Sawyer — Moving Pictures (1981)" },
  { text: "He's old enough to know what's right, but young enough not to choose it.", source: "Tom Sawyer — Moving Pictures (1981)" },
  { text: "A to-do list a mile long, and a me-to-do list a mile long too, but I'm lazy today. But I'm being productive in my laziness.", source: "Neil Peart — Roadshow" },
  { text: "Changes aren't permanent — but change is.", source: "Tom Sawyer — Moving Pictures (1981)" },
  { text: "Wheels within wheels in a spiral array, a pattern so grand and complex.", source: "Natural Science — Permanent Waves (1980)" },
  { text: "Begin the day with a friendly voice, a companion unobtrusive.", source: "The Spirit of Radio — Permanent Waves (1980)" },
  { text: "I see the middle ground, but the edges pull me in.", source: "The Analog Kid — Signals (1982)" },
  { text: "Growing up, it all seems so one-sided. Opinions all provided, the future pre-decided.", source: "Subdivisions — Signals (1982)" },
  { text: "When I leave I don't know what I'm hoping to find. When I leave I don't know what I'm leaving behind.", source: "Finding My Way — Rush (1974)" },
  { text: "Invisible airwaves crackle with life, bright antennae bristle with the energy.", source: "The Spirit of Radio — Permanent Waves (1980)" },
  { text: "I'm not giving in to security under pressure. I'm not missing out on the promise of adventure.", source: "The Enemy Within — Grace Under Pressure (1984)" },
  { text: "In a world of magnets and miracles.", source: "The Color of Right — Test for Echo (1996)" },
  { text: "No one gets to their heaven without a fight.", source: "BU2B — Clockwork Angels (2012)" },
  { text: "What is a master but a master student? And if that's true, then there's a blue sky waiting.", source: "Tai Shan — Hold Your Fire (1987)" },
  { text: "Better the pride that resides in a citizen of the world, than the pride that divides when a colorful rag is unfurled.", source: "Territories — Power Windows (1985)" },
  { text: "Turn around and walk the razor's edge.", source: "The Razor's Edge — Snakes & Arrows (2007)" },
  { text: "The future disappears into memory, with only a moment between. Forever dwells in that moment, hope is what remains to be seen.", source: "The Garden — Clockwork Angels (2012)" },
];
