export const TRIVIA_QUESTIONS = [
  // Easy
  { q: "What city is Rush originally from?", a: "Toronto (Willowdale), Ontario, Canada", difficulty: "easy" },
  { q: "Who replaced John Rutsey as Rush's drummer in 1974?", a: "Neil Peart", difficulty: "easy" },
  { q: "What is the name of Rush's iconic 1976 concept album about a dystopian future?", a: "2112", difficulty: "easy" },
  { q: "What instrument does Geddy Lee primarily play?", a: "Bass guitar (he also plays keyboards and sings)", difficulty: "easy" },
  { q: "What was Rush's first album?", a: "Rush (self-titled, 1974)", difficulty: "easy" },
  { q: "Which Rush song opens with the famous synth riff and the line 'Begin the day with a friendly voice'?", a: "The Spirit of Radio", difficulty: "easy" },
  { q: "What are the nicknames Alex Lifeson and Geddy Lee use for each other?", a: "Lerxst (Alex) and Dirk (Geddy)", difficulty: "easy" },
  { q: "What year did Neil Peart pass away?", a: "January 7, 2020", difficulty: "easy" },
  { q: "What was Rush's final tour called?", a: "R40 (2015)", difficulty: "easy" },
  { q: "Which Rush song features the lyrics 'If you choose not to decide, you still have made a choice'?", a: "Freewill", difficulty: "easy" },
  { q: "What is the name of Geddy Lee's autobiography?", a: "My Effin' Life", difficulty: "easy" },
  { q: "What Rush song is an instrumental featuring complex time signatures, named after Toronto Pearson Airport's code?", a: "YYZ", difficulty: "easy" },
  { q: "Which member of Rush wrote the majority of the band's lyrics?", a: "Neil Peart", difficulty: "easy" },
  { q: "What is the name of the album that features 'Tom Sawyer' and 'Red Barchetta'?", a: "Moving Pictures (1981)", difficulty: "easy" },
  { q: "What did Alex Lifeson famously say during his Rock and Roll Hall of Fame / Juno Awards speech?", a: "Blah Blah Blah (repeated for several minutes)", difficulty: "easy" },

  // Medium
  { q: "What is the subtitle of the '2112' suite's first movement?", a: "Overture", difficulty: "medium" },
  { q: "Which Rush album marked their shift toward a more synthesizer-driven sound?", a: "Signals (1982)", difficulty: "medium" },
  { q: "What Neil Peart book chronicles his motorcycle journey across North America after personal tragedy?", a: "Ghost Rider: Travels on the Healing Road", difficulty: "medium" },
  { q: "What is the name of the fictional character who discovers a guitar in the '2112' suite?", a: "The protagonist (unnamed) / The Hero — he discovers an ancient guitar", difficulty: "medium" },
  { q: "Which album features the songs 'Subdivisions' and 'New World Man'?", a: "Signals (1982)", difficulty: "medium" },
  { q: "What science fiction author inspired the concept behind 2112?", a: "Ayn Rand (based on her novella Anthem)", difficulty: "medium" },
  { q: "What was the last studio album Rush released?", a: "Clockwork Angels (2012)", difficulty: "medium" },
  { q: "Name the two parts of the 'Cygnus X-1' epic that spans two albums.", a: "Book I: The Voyage (A Farewell to Kings) and Book II: Hemispheres (Hemispheres)", difficulty: "medium" },
  { q: "Which Rush album was produced by Peter Collins and features the song 'Marathon'?", a: "Power Windows (1985)", difficulty: "medium" },
  { q: "What is the significance of the 'Starman' logo used by Rush?", a: "It represents the individual standing against the masses — the man and the star from 2112", difficulty: "medium" },
  { q: "Which Rush album features a red car on the cover and includes the song 'Driven'?", a: "Test for Echo (1996)", difficulty: "medium" },
  { q: "What was the name of Rush's live album/concert film from their R40 tour?", a: "R40 Live", difficulty: "medium" },
  { q: "Which song from 'A Farewell to Kings' features a classical guitar introduction?", a: "A Farewell to Kings (the title track) — though 'Closer to the Heart' is also from this album", difficulty: "medium" },
  { q: "What album features 'The Trees' — the song about maples and oaks?", a: "Hemispheres (1978)", difficulty: "medium" },
  { q: "Which Rush album was their first to reach #1 in Canada?", a: "Vapor Trails (2002)", difficulty: "medium" },
  { q: "What is the name of the epic instrumental on 'A Farewell to Kings'?", a: "Xanadu", difficulty: "medium" },
  { q: "Which album has the songs 'Animate' and 'Stick It Out'?", a: "Counterparts (1993)", difficulty: "medium" },
  { q: "What guitar is Alex Lifeson most closely associated with?", a: "Gibson ES-355 (white)", difficulty: "medium" },
  { q: "Name the Rush album that was recorded after a 5-year hiatus following Neil's personal tragedies.", a: "Vapor Trails (2002)", difficulty: "medium" },
  { q: "What is the name of the instrumental on 'Hemispheres'?", a: "La Villa Strangiato (An Exercise in Self-Indulgence)", difficulty: "medium" },

  // Hard
  { q: "What was the original name of the band before they settled on 'Rush'?", a: "The band was always called Rush — but earlier lineups included Jeff Jones on bass before Geddy Lee", difficulty: "hard" },
  { q: "What is the time signature of the main riff in 'Tom Sawyer'?", a: "7/8 (alternating with 4/4 sections)", difficulty: "hard" },
  { q: "Which Rush song was inspired by a short story by John Barth?", a: "Red Barchetta (inspired by 'A Nice Morning Drive' by Richard Foster)", difficulty: "hard" },
  { q: "Name the drummer who played on Rush's debut album before Neil Peart.", a: "John Rutsey", difficulty: "hard" },
  { q: "What is Neil Peart's drum kit brand of choice for most of his career?", a: "DW (Drum Workshop) — earlier he used Slingerland and then Ludwig and Tama", difficulty: "hard" },
  { q: "Which Rush song references the Cygnus X-1 black hole and spans two albums?", a: "Cygnus X-1 — Book I on A Farewell to Kings and Book II on Hemispheres", difficulty: "hard" },
  { q: "What is the name of Alex Lifeson's side project/band?", a: "Victor (solo album, 1996) — he also had Big Dirty Band and Envy of None", difficulty: "hard" },
  { q: "Which Rush album was the first to feature Neil Peart on drums?", a: "Fly by Night (1975)", difficulty: "hard" },
  { q: "What is the full subtitle of 'La Villa Strangiato'?", a: "An Exercise in Self-Indulgence", difficulty: "hard" },
  { q: "What concept ties together the songs on 'Clockwork Angels'?", a: "A steampunk story about a young man's journey through a world controlled by a Watchmaker, seeking meaning and purpose", difficulty: "hard" },
  { q: "Which Hemispheres track retells the story of Apollo and Dionysus?", a: "Hemispheres (the title track / Cygnus X-1 Book II)", difficulty: "hard" },
  { q: "What was unique about the 'Vapor Trails' album that was later corrected in a remix?", a: "It was heavily clipped/distorted in mastering (the 'loudness war'). A remixed version was released in 2013.", difficulty: "hard" },
  { q: "Name the Rush song that features a reggae-influenced bridge section on 'Signals'.", a: "Digital Man", difficulty: "hard" },
  { q: "What is Geddy Lee's real first name?", a: "Gary (Gary Lee Weinrib)", difficulty: "hard" },
  { q: "Which Rush song was their highest-charting single in the US?", a: "New World Man (#21 on Billboard Hot 100, 1982)", difficulty: "hard" },
  { q: "What Toronto venue did Rush play their first major hometown gigs at in the early 70s?", a: "The Gasworks (and later Massey Hall)", difficulty: "hard" },
  { q: "What was the working title of 'Moving Pictures' during recording?", a: "It was always Moving Pictures — a play on words (motion pictures / emotionally moving)", difficulty: "hard" },
  { q: "Name the three movements that make up the 'Fear' series spread across multiple Rush albums.", a: "Part I: The Enemy Within (Grace Under Pressure), Part II: The Weapon (Signals), Part III: Witch Hunt (Moving Pictures), Part IV: Freeze (Vapor Trails)", difficulty: "hard" },
];
